CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98
Include = -I/ 
SRCS = main.cpp Zombie.cpp newZombie.cpp randomChump.cpp
OBJS = ${SRCS:.cpp=.o}
NAME = zombie

${NAME}: ${OBJS}
	${CXX} ${CXXFLAGS} ${OBJS} -o ${NAME}

all: ${NAME}

clean: 
	rm -f ${OBJS}
fclean: clean
	rm -f ${NAME}

re: fclean all

.PHONY: all clean fclean re